Bump spring from 2.1.1 to 4.0.0
spring needs to be at least 3.0.0 to be compatible with rails 7:
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-1-to-rails-7-0-spring

Prior to this upgrade, a rails console failed to open with error:
undefined method 'mechanism=' for ActiveSupport::Dependencies:Module